-- Mover todos los documentos de esta nueva lista al silo 'personal' y categorizarlos como 'norma'

UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Captación de Personal%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Requisición de personal%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Aprobación de publicación de vacantes en proceso de captación%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Entrevista a Candidatos%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Pruebas Psicotecnicas%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Assesment Center%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Exámen Pre-Empleo%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Oferta Salarial%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Inducción a Colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Uso del Uniforme%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Uso del Comedor de la Empresa%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Evaluación de Competencias%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Retroalimentación para el Desarrollo%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Capacitacion del personal%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Programa de Pasantias%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Sucesión de Personal%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Movilidad de colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Matriz de crecimiento%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Estructuras Organizacionales%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Descripcion de Cargos%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Compensación salarial%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Administración de escala salarial%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Administración de Remuneración Variable%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Viaticos de colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Gestión de Reconocimiento%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma  Reconocimiento por años de servicio%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Beneficios del Colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Vacaciones colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Préstamos a Colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Gestion de solicitudes del colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Actividades de Bienestar al Colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Comunicaciones internas al Colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Gestión de Obligaciones Gubernamentales de Personal%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Asociación Solidarista de las Empresas de Mayoreo en Costa Rica%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Ingreso del colaborador%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Procedimiento Ascensos y Promociones%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Contratos de Trabajo a Colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Procedimiento suspenciones de colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Procedimiento Desincorporación de Colaboradores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Reporte del Colaborador de Accidentes Laborales%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Investigación de Accidentes Laborales%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Seguimiento de Gestión de Seguridad y Salud%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Equipamiento de primeros Auxilios%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Procedimiento Evaluación de agua potable%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Uso de equipos de protección Personal (EPP)%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Almacenamiento en Tarimas%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Uso seguro de Montacargas%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Revisión de Camiones, Montacargas, Apiladores y Otros Vehículos de la Empresa%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Control de Acceso a las Instalaciones%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Mantenimiento de la Planta Eléctrica%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Uso de Lockers en Instalaciones de la Empresa%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Revisión del Sistema contra Incendio del Edificio%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Seguridad Vehicular%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Certificación Interna de Montacarguistas y Apiladores%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Apertura y Cierre de CEDI%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Manejo Sistema CCTV%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Sistema de Alarma%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Administración del servicio de Vigilancia%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Norma Para Seguridad de Contratistas%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Protocolo para Conato de Incendio%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Protocolo de respuestas ante Sismos%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Protocolo para el manejo de Sustancias peligrosas%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Protocolo de Vehiculos cargados para despacho%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Trabajo Alto Riesgo%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Uso del Estacionamiento de la Empresa%';
UPDATE public.documents SET silo = 'personal', doc_type = 'norma' WHERE TRIM(title) ILIKE 'Protocolo para continuidad operativa%';
